version: '3.9'

services:
  goalbot:
    build: .
    container_name: goal-reminder-bot
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Kolkata
      - BOT_TOKEN=7576181421:AAH_pmVimWYuAdW9KSZ94AcuBhtG504XmrA
      - CHAT_ID=6501087487
      - PORT=3000
    volumes:
      - appdata:/app/data
    restart: unless-stopped

volumes:
  appdata:
    driver: local
