version: '3.9'

services:
  web:
    build: ./web
    container_name: goal-reminder-web
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Kolkata
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
      - PORT=3000
    volumes:
      - appdata:/app/data
    restart: unless-stopped

  telegrambot:
    build: ./telegrambot
    container_name: goal-reminder-bot
    environment:
      - TZ=Asia/Kolkata
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
    volumes:
      - appdata:/app/data
    restart: unless-stopped

volumes:
  appdata:
